language: node_js
node_js:
  - "10"
  - "12"
  - "13"
  - "14"
dist: trusty
sudo: false

install:
  - npm ci

cache:
  directories:
    - node_modules

script:
  - npm audit --production
  - npm run sass
